cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED DVC_RUNTIME_VARIANT OR DVC_RUNTIME_VARIANT STREQUAL "")
  message(FATAL_ERROR "DVC_RUNTIME_VARIANT is not set")
endif()

if(NOT DEFINED DVC_RUNTIME_VARIANT_FILE OR DVC_RUNTIME_VARIANT_FILE STREQUAL "")
  message(FATAL_ERROR "DVC_RUNTIME_VARIANT_FILE is not set")
endif()

file(WRITE "${DVC_RUNTIME_VARIANT_FILE}"
"# Generated by CMake. Used by bootstrap.py to select the runtime mode.\n"
"DVC_RUNTIME_VARIANT = \"${DVC_RUNTIME_VARIANT}\"\n"
)
